ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    skip: []
    submodules: false

repos:
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v11.1.0
        hooks:
              - id: clang-format
                # Using the pre-commit stage to simplify invocation of all
                # other hooks simultaneously (via any other hook stage).  This
                # can be removed if we also move to running clang-format
                # entirely through pre-commit.
                stages: [commit]
                name: clang-format
                description: Format files with ClangFormat.
                entry: clang-format
                language: system
                files: \.(cu|cuh|h|hpp|cpp|inl)$
                'types_or': [file]
                args: ['-fallback-style=none', '-style=file', '-i']

default_language_version:
      python: python3
